// <auto-generated />
namespace MovieManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedFilmeTable_AddedGeneroTable_AddedLoggin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedFilmeTable_AddedGeneroTable_AddedLoggin));
        
        string IMigrationMetadata.Id
        {
            get { return "201804280312092_AddedFilmeTable_AddedGeneroTable_AddedLoggin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
